"""add resend_api_key to user_settings

Revision ID: 66b8a4385583
Revises: 095949a1ca95
Create Date: 2026-02-07 21:42:00.219812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b8a4385583'
down_revision: Union[str, Sequence[str], None] = '095949a1ca95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('resend_api_key', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'resend_api_key')
    # ### end Alembic commands ###
